server:
  port: 80
#配置Druid数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ""
    type: com.alibaba.druid.pool.DruidDataSource



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #设置实体类所对应表的统一前缀
      table-prefix: t_
      # 设置统一的主键生成策略
      id-type: auto
  # 配置类型别名所对应的包
  type-aliases-package: com.example.myblog.pojo


#设置日志级别
logging:
  level:
    root: info
    com.example.myblog: debug
  #日志文件的位置
  #file:
   #name: blog.log


